@startuml
'https://plantuml.com/sequence-diagram



Class Main{
Questions?
Scanner
}
Class CancerProgram{
ChanceProcent

}
Class User{
LogIn
Questioner
Symptoms
Sickness
Diet
LifeStyle
Stress
Depression
}
Class CancerInfo{
Information about
different kind of Cancer

}

Class DBConnector{
Data Banks reader
}

Main *-- DBConnector
Main *-- CancerProgram
CancerProgram *-- User
User *-- CancerInfo

@enduml