@startuml
'https://plantuml.com/sequence-diagram



Class Main{
Questions?
Scanner;
}

Class CancerProgram{

ChanceProcent;
SearchBySymptoms();
SearchByCancerSickness();
}

Class User{
UserName;
PassWord;
LogIn;
String Questioner;
Symptoms;
Sickness;
LifeStyle;
}

Class CancerInfo{

Information about
different kind of Cancer
}

Class DBConnector{
List<Symptoms>symptoms;
List<CancerSickness> cs;
List<User>users;
Data Banks reader
}

Main *-- DBConnector
Main *-- CancerProgram
CancerProgram *-- User
User *-- CancerInfo

@enduml