@startuml
'https://plantuml.com/sequence-diagram



Class Main{
Questions?
Scanner;
List<User>users = new Arraylist<>();
}

Class CancerProgram{
ChanceProcent;
SearchByCancerInfo();
SearchBySymptoms();
SearchByCancerSickness();
}

Class User{
UserName;
PassWord;
GetUserName;
GetPassWord;
LogIn;
String Questioner;
Symptoms;
Sickness;
LifeStyle;
public User (userName, passWord)
this.UserName = userName;
this.PassWord = passWord;
this.Cancer = new ArrayList<>();
}


Class CancerInfo{

Information about
different kind of Cancer
}

Class DBConnector{
List<CancerInfo> ci;
List<User>users;
Data Banks reader
}

Main *-- DBConnector
Main *-- CancerProgram
CancerProgram *-- User
DBConnector *-- CancerInfo
CancerProgram *-- CancerInfo

@enduml